CREATE DATABASE bookstore;

CREATE TABLE movies (
    id INT NOT NULL AUTO_INCREMENT, name VARCHAR(255) NOT NULL, director VARCHAR(255) NOT NULL, rating INT NOT NULL, username VARCHAR(255) NOT NULL, PRIMARY KEY (id)
);

CREATE TABLE users (
    id INT NOT NULL AUTO_INCREMENT, name VARCHAR(255) NOT NULL, username VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id)
);